# Gate A1 golden capture harness. Derives the golden fixture from the
# CERTIFIED fair-campaign records (the winning 2026-07-24 attempt 5 run),
# never from hand-authored values: the archived runner copy is SHA-verified
# against campaign-complete.json, its env-construction block is extracted by
# anchored regex (fail-closed on any shape drift), and the parameter values
# come from the pilot's own printed CONFIG lines in the certified device
# logs. Rerunning this script must reproduce the committed fixture
# byte-for-byte; the reproducibility gate in run_cold_gates.ps1 asserts it.
param(
    [string]$ArtifactDir = 'C:\Users\Jack\IdeaProjects\mtg-kernel-fair-campaign-harness-fable\artifacts\fair-sparse-campaign\20260724T1647536950174Z-fair-sparse-f31-b31-f32-6f53c1e58af1',
    [string]$OutputPath = (Join-Path $PSScriptRoot 'a1-golden-legacy-env.json')
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Pinned identity of the certified run (TO-CODEX.md 2026-07-24 14:15 entry).
$expectedCampaignCompleteSha = 'aa6034060597e782c1e2415af103cf333afc04c62bce9ebec5171331eec69173'

function Get-Sha256HexLocal { param([string]$Path)
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

$campaignCompletePath = Join-Path $ArtifactDir 'campaign-complete.json'
$runnerCopyPath = Join-Path $ArtifactDir '00-runner-starting-copy.ps1'
foreach ($required in @($campaignCompletePath, $runnerCopyPath)) {
    if (-not (Test-Path -LiteralPath $required)) { throw "certified artifact missing: $required" }
}
$campaignCompleteSha = Get-Sha256HexLocal -Path $campaignCompletePath
if ($campaignCompleteSha -cne $expectedCampaignCompleteSha) {
    throw "campaign-complete.json sha $campaignCompleteSha does not match the pinned certified identity"
}
$campaignComplete = Get-Content -LiteralPath $campaignCompletePath -Raw | ConvertFrom-Json
$runnerCopySha = Get-Sha256HexLocal -Path $runnerCopyPath
if ($runnerCopySha -cne $campaignComplete.runner_starting_sha256.ToLowerInvariant()) {
    throw 'archived runner copy sha does not match campaign-complete.json runner_starting_sha256'
}

# Extract the env-construction block from the SHA-verified runner copy.
# Anchored to the exact assignment shape; any drift fails closed.
$runnerText = Get-Content -LiteralPath $runnerCopyPath -Raw
$envBlockPattern = '(?s)CUDA_VISIBLE_DEVICES = \$null\s*' +
    'MULTIRUN_RUNS = \$definition\.runs\.ToString\(\)\s*' +
    'MULTIRUN_UPDATES = \$ExpectedUpdates\.ToString\(\)\s*' +
    'MULTIRUN_WORKERS = \$ExpectedWorkers\.ToString\(\)\s*' +
    'MULTIRUN_SESSIONS = \$ExpectedSessions\.ToString\(\)\s*' +
    'MULTIRUN_BROKER_TARGET = \$ExpectedBrokerTarget\.ToString\(\)\s*' +
    'MTG_KERNEL_PILOT_CUDA_ORDINAL = \$definition\.ordinal\.ToString\(\)'
if ($runnerText -cnotmatch $envBlockPattern) {
    throw 'archived runner env-construction block does not match the anchored expected shape'
}

# Pilot-printed CONFIG lines from the certified device logs: the running
# binary's self-reported parameters, the strongest available record. Every
# log is hash-verified against campaign-complete.json's recorded
# device_results[].validation.stdout_sha256 BEFORE any line is trusted.
$configLinePattern = 'MULTIRUN CONFIG runs=(\d+) updates=(\d+) topology=(\d+)x(\d+) broker_target=(\d+)'
$configLines = [ordered]@{}
$logHashes = [ordered]@{}
foreach ($probe in @(
    @{ arm = 'F31'; device = 0 }, @{ arm = 'F31'; device = 1 },
    @{ arm = 'F32'; device = 0 }, @{ arm = 'F32'; device = 1 }
)) {
    $logPath = Join-Path $ArtifactDir ("{0}\device{1}.stdout.log" -f $probe.arm, $probe.device)
    $armEntry = @($campaignComplete.arm_results | Where-Object { $_.arm -ceq $probe.arm })
    if ($armEntry.Count -ne 1) { throw "expected exactly one arm_results entry for $($probe.arm)" }
    $deviceEntry = @($armEntry[0].device_results | Where-Object { $_.device_ordinal -eq $probe.device })
    if ($deviceEntry.Count -ne 1) { throw "expected exactly one device_results entry for $($probe.arm) device $($probe.device)" }
    $recordedSha = $deviceEntry[0].validation.stdout_sha256.ToLowerInvariant()
    $actualSha = Get-Sha256HexLocal -Path $logPath
    if ($actualSha -cne $recordedSha) { throw "device log $logPath sha $actualSha does not match the recorded certified hash $recordedSha" }
    $key = "{0}_device{1}" -f $probe.arm.ToLowerInvariant(), $probe.device
    $logHashes[$key] = $actualSha
    $line = (Select-String -LiteralPath $logPath -Pattern $configLinePattern | Select-Object -First 1)
    if ($null -eq $line) { throw "no CONFIG line in $logPath" }
    $configLines[$key] = $line.Line.Trim()
    if ($line.Line -cnotmatch 'updates=64 topology=2x32 broker_target=16') {
        throw "certified CONFIG line in $logPath does not carry the expected 64/2x32/16 parameters"
    }
}

$fixture = [ordered]@{
    schema = 'multirun-operating-point-gate-a1-golden/v2'
    provenance = [ordered]@{
        derivation = 'Generated by capture_a1_golden.ps1; never hand-edit. Env mapping extracted by anchored regex from the SHA-verified archived runner copy of the certified 2026-07-24 fair campaign (attempt 5); parameter values cross-checked against the pilot-printed CONFIG lines in the certified device logs.'
        artifact_dir = $ArtifactDir
        campaign_complete_sha256 = $campaignCompleteSha
        runner_starting_sha256 = $runnerCopySha
        device_log_stdout_sha256 = $logHashes
        certified_config_lines = $configLines
    }
    certified_env = [ordered]@{
        managed_names = [ordered]@{
            CUDA_VISIBLE_DEVICES = 'cleared'
            MULTIRUN_RUNS = 'per-device run count'
            MULTIRUN_UPDATES = '64'
            MULTIRUN_WORKERS = '2'
            MULTIRUN_SESSIONS = '32'
            MULTIRUN_BROKER_TARGET = '16'
            MTG_KERNEL_PILOT_CUDA_ORDINAL = 'per-device ordinal'
        }
        unmanaged_note = 'The certified arms set ONLY the seven names above. Seeds (MULTIRUN_BASE_SEED/SEED_OFFSET), stores (MULTIRUN_STORE_PARENT), CUDA_DEVICE_ORDER, and every mode knob were left to the ambient environment, whose cleanliness the campaign verified through its ambient-preauthorization machinery (ambient-preauthorized-set.json per arm).'
    }
    v1_divergences = @(
        [ordered]@{
            names = @('CUDA_VISIBLE_DEVICES', 'MTG_KERNEL_PILOT_CUDA_ORDINAL', 'CUDA_DEVICE_ORDER')
            certified = 'CUDA_VISIBLE_DEVICES cleared; placement via MTG_KERNEL_PILOT_CUDA_ORDINAL = device ordinal; CUDA_DEVICE_ORDER unmanaged'
            v1 = 'CUDA_VISIBLE_DEVICES = pinned device UUID; MTG_KERNEL_PILOT_CUDA_ORDINAL always 0; CUDA_DEVICE_ORDER = PCI_BUS_ID'
            justification = 'The bridge ordinal parse is lenient (absent/unparsable silently means 0, bridge.rs:418-425): under certified-style placement a typo stacks every process on device 0. UUID masking pins device identity in-record and makes the lenient parse unreachable. Placement mechanism changes; run semantics do not. Gate A3 (store byte-identity) and both confirmation legs validate on-device equivalence.'
        },
        [ordered]@{
            names = @('MULTIRUN_BASE_SEED', 'MULTIRUN_SEED_OFFSET')
            certified = 'unset; both device processes fell to pilot defaults (base 424242, offset 0), so cross-process run seeds overlapped, harmless for ephemeral throughput arms'
            v1 = 'explicit base_seed from config plus cumulative per-process offsets (the S1-proven scheme), collision-free by construction'
            justification = 'v1 runs durable stores; overlapping run seeds across processes would be a correctness defect there.'
        },
        [ordered]@{
            names = @('MULTIRUN_STORE_PARENT')
            certified = 'unset; ephemeral per-run stores'
            v1 = 'explicit fresh-root durable parent per process'
            justification = 'Productized launches keep stores for post-run validation and eps/s recomputation.'
        },
        [ordered]@{
            names = @('all mode knobs and MULTIRUN_EXECUTION_MODE')
            certified = 'unmanaged, relied on verified-clean ambient environment'
            v1 = 'every whitelist name explicitly set or explicitly cleared per process'
            justification = 'Replaces ambient trust with per-name explicitness; an inherited shell cannot leak a mode into a throughput run.'
        }
    )
}

$json = $fixture | ConvertTo-Json -Depth 6
[IO.File]::WriteAllText($OutputPath, $json + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
Write-Output "golden written: $OutputPath"
