"""Generate an independent, correctly-rounded oracle table for
`mtg-kernel/src/deterministic_math_v1.rs`'s `tanh_f32_v1`.

This is a verification tool, not a build-time or runtime dependency of the
Rust crate: its only output is the `(input_bits, expected_bits)` const
array pasted directly into that file's
`oracle_correctly_rounded_comparison_v1` test (see the comment there
pointing back at this script). It is intentionally independent of the
Rust implementation under test: every expected value here is computed
from `mpmath` at 50 decimal digits of precision, then rounded to the
nearest `f32` (round-to-nearest-even) by a single, safe double-rounding
through `f64` (`f64` has 52 mantissa bits vs. `f32`'s 23, so `f64`'s own
rounding error, on the order of `2^-52`, cannot flip an `f32`-level
round-to-nearest decision, which only needs to distinguish values to
within about `2^-24`).

Requires `mpmath` (e.g. `pip install mpmath` or `uv pip install mpmath`
inside this project's virtualenv). Deliberately not added to this
project's `pyproject.toml` dependencies: this is a one-off oracle
generator run by a human during review, not a runtime or test-time
dependency of the shipped package.

Usage: `python python/tools/generate_deterministic_math_v1_oracle_goldens.py`
Prints a Rust `const` array literal to stdout, ready to paste into the
test module. Deterministic: the sampled bit patterns are all fixed,
explicit constants below, not derived from any random seed.
"""

from __future__ import annotations

import struct

import mpmath as mp

mp.mp.dps = 50


def f32_bits(value: float) -> int:
    return struct.unpack("<I", struct.pack("<f", float(value)))[0]


def bits_to_f32(bits: int) -> float:
    return struct.unpack("<f", struct.pack("<I", bits & 0xFFFFFFFF))[0]


def correctly_rounded_tanh_bits(input_bits: int) -> int:
    x = bits_to_f32(input_bits)
    if x != x:  # NaN: not part of this oracle table (tanh_f32_v1's NaN
        raise ValueError("NaN inputs are not part of the oracle table")
    if x == float("inf"):
        return f32_bits(1.0)
    if x == float("-inf"):
        return f32_bits(-1.0)
    high_precision = mp.tanh(mp.mpf(x))
    return f32_bits(float(high_precision))  # safe double-round, see module doc


# Small-linear seam constant (TANH_SMALL_LINEAR_THRESHOLD_V1 = 2^-12).
SMALL_SEAM_BITS = 0x3980_0000
# Saturation seam constant (TANH_SATURATION_THRESHOLD_V1), the true
# mpmath-verified crossover found by binary search in this same review.
SAT_SEAM_BITS = 0x4110_2CB4


def build_table() -> list[int]:
    bits_set: set[int] = set()

    # 1. Both seams, 64 consecutive bit patterns each (32 below, 32 at/above).
    for seam in (SMALL_SEAM_BITS, SAT_SEAM_BITS):
        for offset in range(-32, 32):
            bits_set.add((seam + offset) & 0xFFFFFFFF)

    # 2. Subnormals: smallest, largest, and several representative points
    #    in between, both signs.
    subnormal_bits = [0x0000_0001, 0x0000_0100, 0x0040_0000, 0x0055_5555, 0x007F_FFFF]
    for b in subnormal_bits:
        bits_set.add(b)
        bits_set.add(b | 0x8000_0000)

    # 3. Passthrough region: strictly inside the small-linear seam (not at
    #    the boundary, which is already covered above), spread across
    #    magnitudes, both signs.
    for exponent in range(-40, -12):
        x = 2.0**exponent
        b = f32_bits(x)
        bits_set.add(b)
        bits_set.add(b | 0x8000_0000)

    # 4. Polynomial interior: varied exponents between the two seams, many
    #    points per octave, both signs.
    for exponent in range(-11, 4):
        for mantissa_step in range(12):
            frac = 1.0 + mantissa_step * (1.0 / 12.0)
            x = (2.0**exponent) * frac
            if x >= bits_to_f32(SAT_SEAM_BITS):
                continue
            b = f32_bits(x)
            bits_set.add(b)
            bits_set.add(b | 0x8000_0000)

    # 5. Saturation region beyond the seam, including extremes.
    for x in [9.02, 9.1, 9.5, 10.0, 12.0, 20.0, 50.0, 100.0, 1000.0, 1.0e10, 3.4e38]:
        b = f32_bits(x)
        bits_set.add(b)
        bits_set.add(b | 0x8000_0000)
    bits_set.add(f32_bits(float("inf")))
    bits_set.add(f32_bits(float("-inf")))

    # 6. Zero and its sign twin (also covered by the module's own golden
    #    battery, included here for the oracle table's own completeness).
    bits_set.add(0x0000_0000)
    bits_set.add(0x8000_0000)

    return sorted(bits_set)


def main() -> None:
    table = build_table()
    pairs = [(b, correctly_rounded_tanh_bits(b)) for b in table]

    print(f"// Generated by python/tools/generate_deterministic_math_v1_oracle_goldens.py")
    print(f"// {len(pairs)} entries; do not hand-edit, regenerate instead.")
    print(f"const ORACLE_TABLE_V1: [(u32, u32); {len(pairs)}] = [")
    for input_bits, expected_bits in pairs:
        print(f"    (0x{input_bits:08x}, 0x{expected_bits:08x}),")
    print("];")


if __name__ == "__main__":
    main()
