//! Offline contract for a player-visible MTGO adapter.
//!
//! This crate intentionally contains no capture, process inspection, network
//! inspection, accessibility enumeration, or input implementation.

#![forbid(unsafe_code)]

pub use mtg_kernel::rl::{
    ActionSemanticV1, CardPrivateV1, CardPublicV2, CardStableRefV1, KnownLibraryCardV4,
    ObjectRelationPublicV4, ObservationV5, PlayerSeatV1, StackItemKindV2, StackItemPublicV2,
    TargetRefV1, ZoneIndependentStepV1,
};

mod action_resolution;
mod authorization_correspondence;
mod calibration_trace;
mod capture_contract;
mod card_correspondence;
mod competitive_duel_lifecycle_evaluation;
mod competitive_event_listing;
mod competitive_event_listing_evaluation;
mod competitive_event_record;
mod competitive_event_record_evaluation;
mod competitive_gameplay_scope;
mod competitive_lifecycle;
mod competitive_match_memory;
mod competitive_navigation_evaluation;
mod competitive_pregame_classification;
mod competitive_pregame_evaluation;
mod competitive_pregame_public_context;
mod competitive_pregame_public_context_classification;
mod competitive_pregame_public_context_evaluation;
mod competitive_sideboard;
mod competitive_sideboard_evaluation;
mod competitive_wiring_readiness;
mod contract;
mod direct_source_duel_projection;
mod direct_visible_competitive_gameplay;
mod direct_visible_duel_scoring;
mod direct_visible_gameplay_postcondition;
mod duel_action_postcondition;
mod duel_annotation_set;
mod duel_calibration_corpus;
mod duel_gesture;
mod duel_gesture_evaluation;
mod duel_model_scoring;
mod duel_perception_evaluation;
mod dxgi_artifact;
mod dxgi_observed_decision;
mod first_main_kernel_context;
mod first_main_kernel_coverage;
mod first_main_legal_actions;
mod first_main_reconstruction;
mod mock;
mod model_deployment;
mod model_scoring;
mod object_incarnation;
mod offline_bottom_six_initial;
mod offline_bottom_six_reflow;
mod offline_bottom_six_state;
mod offline_bottom_six_state_v2;
mod offline_bottom_six_state_v3;
mod offline_bottoming;
mod offline_first_main;
mod offline_mulligan_ladder;
mod offline_perception;
mod offline_play_land_hand_reflow;
mod offline_pregame_episode;
mod offline_visible_card_identity;
mod player_visible_attacker_deliberation;
mod player_visible_attacker_execution;
mod player_visible_attacker_scoring;
mod player_visible_blocker_deliberation;
mod player_visible_blocker_scoring;
mod player_visible_duel_gesture;
mod player_visible_duel_input;
mod player_visible_duel_scoring;
mod player_visible_gameplay_postcondition;
mod player_visible_multi_attacker_blocker_deliberation;
mod player_visible_multi_attacker_blocker_execution;
mod reconstruction_audit;
mod validation;
mod visible_duel_viewmodel_broker_protocol;
mod visible_duel_viewmodel_producer_audit;
mod visible_duel_viewmodel_surface;
mod visible_game_log_action_corroboration;
mod visible_game_log_file;
mod visible_game_log_semantics;
mod visible_history;

pub use action_resolution::*;
pub use authorization_correspondence::*;
pub use calibration_trace::*;
pub use capture_contract::*;
pub use card_correspondence::*;
pub use competitive_duel_lifecycle_evaluation::*;
pub use competitive_event_listing::*;
pub use competitive_event_listing_evaluation::*;
pub use competitive_event_record::*;
pub use competitive_event_record_evaluation::*;
pub use competitive_gameplay_scope::*;
pub use competitive_lifecycle::*;
pub use competitive_match_memory::*;
pub use competitive_navigation_evaluation::*;
pub use competitive_pregame_classification::*;
pub use competitive_pregame_evaluation::*;
pub use competitive_pregame_public_context::*;
pub use competitive_pregame_public_context_classification::*;
pub use competitive_pregame_public_context_evaluation::*;
pub use competitive_sideboard::*;
pub use competitive_sideboard_evaluation::*;
pub use competitive_wiring_readiness::*;
pub use contract::*;
pub use direct_source_duel_projection::*;
pub use direct_visible_competitive_gameplay::*;
pub use direct_visible_duel_scoring::*;
pub use direct_visible_gameplay_postcondition::*;
pub use duel_action_postcondition::*;
pub use duel_annotation_set::*;
pub use duel_calibration_corpus::*;
pub use duel_gesture::*;
pub use duel_gesture_evaluation::*;
pub use duel_model_scoring::*;
pub use duel_perception_evaluation::*;
pub use dxgi_artifact::*;
pub use dxgi_observed_decision::*;
pub use first_main_kernel_context::*;
pub use first_main_kernel_coverage::*;
pub use first_main_legal_actions::*;
pub use first_main_reconstruction::*;
pub use mock::*;
pub use model_deployment::*;
pub use model_scoring::*;
pub use object_incarnation::*;
pub use offline_bottom_six_initial::*;
pub use offline_bottom_six_reflow::*;
pub use offline_bottom_six_state::*;
pub use offline_bottom_six_state_v2::*;
pub use offline_bottom_six_state_v3::*;
pub use offline_bottoming::*;
pub use offline_first_main::*;
pub use offline_mulligan_ladder::*;
pub use offline_perception::*;
pub use offline_play_land_hand_reflow::*;
pub use offline_pregame_episode::*;
pub use offline_visible_card_identity::*;
pub use player_visible_attacker_deliberation::*;
pub use player_visible_attacker_execution::*;
pub use player_visible_attacker_scoring::*;
pub use player_visible_blocker_deliberation::*;
pub use player_visible_blocker_scoring::*;
pub use player_visible_duel_gesture::*;
pub use player_visible_duel_input::*;
pub use player_visible_duel_scoring::*;
pub use player_visible_gameplay_postcondition::*;
pub use player_visible_multi_attacker_blocker_deliberation::*;
pub use player_visible_multi_attacker_blocker_execution::*;
pub use reconstruction_audit::*;
pub use validation::*;
pub use visible_duel_viewmodel_broker_protocol::*;
pub use visible_duel_viewmodel_producer_audit::*;
pub use visible_duel_viewmodel_surface::*;
pub use visible_game_log_action_corroboration::*;
pub use visible_game_log_file::*;
pub use visible_game_log_semantics::*;
pub use visible_history::*;
