// Generated by data/flat_policy_v3/generate_contract.py. V5 pins are separate.
pub(crate) const FEATURE_SCHEMA_VERSION_V3: &str = "actor-relative-v6-python-2";
pub(crate) const FEATURE_REGISTRY_VERSION_V3: &str = "rust-observation-v6-action-v5-registry-2";
pub(crate) const FEATURE_CONTRACT_DIGEST_V3: &str = "527db1125fa760076c2e751bb70be74cab21aa4dcb7d558a0b804a597ef8adfd";
pub(crate) const FEATURE_ENCODING_DIGEST_V3: &str = "3ccfd79fe8c4c3916043e931fcb251aed2c3cd8c9c13f31c1112c2af3b855feb";
pub(crate) const FEATURES_SOURCE_SHA256_V3: &str = "5d2c2531bfc4899037379300872d6be3cd9d5d341eace7b7968503a68928d12a";
pub(crate) const FEATURE_DESCRIPTOR_SHA256_V3: &str = "05267741b171e1a83a0cb357b18dac61c502afd6377837c293a1ff78c4bcc0ec";
