"""Regenerate only the explicit V6 successor's immutable feature pins."""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "python"))
from mtg_kernel_rl import features_v6 as features


def generate() -> None:
    directory = Path(__file__).resolve().parent
    source_hash = hashlib.sha256(Path(features.__file__).read_bytes()).hexdigest()
    descriptor = {
        "schema": "flat-policy-v3-feature-contract-3",
        "rich_observation_schema": 6,
        "legal_action_schema": 5,
        "feature_schema_version": features.FEATURE_SCHEMA_VERSION,
        "feature_registry_version": features.FEATURE_REGISTRY_VERSION,
        "feature_contract_digest": features.feature_contract_fingerprint(),
        "feature_encoding_digest": features.encoding_contract_fingerprint(),
        "features_source_path": "python/mtg_kernel_rl/features_v6.py",
        "features_source_sha256": source_hash,
        "model_contract_version": features.MODEL_CONTRACT_VERSION,
        "dimensions": {"state": 219, "object": 98, "edge": 41, "action": 195, "action_ref": 25, "object_groups": 20},
        "encoding": features.EXTENSION_ENCODING_CONTRACT_V6,
        "extension_edge_subroles": {"cost_source": 32, "cost_selected": 33, "search_card": 34, "historical_source": 35,
                                    "pending_ward_payment": 36, "queued_ward_payment": 37},
        "provenance_boundary": "Python validates internal consistency; authoritative Rust production validates actual public history and hidden-state scope.",
        "transfer": "Existing Net8 weights require explicitly labeled feature transfer. Shape equality is not unchanged checkpoint identity or competence evidence.",
    }
    descriptor_bytes = (json.dumps(descriptor, sort_keys=True, indent=2, ensure_ascii=False) + "\n").encode()
    (directory / "feature_contract_v3.json").write_bytes(descriptor_bytes)
    values = {
        "FEATURE_SCHEMA_VERSION_V3": features.FEATURE_SCHEMA_VERSION,
        "FEATURE_REGISTRY_VERSION_V3": features.FEATURE_REGISTRY_VERSION,
        "FEATURE_CONTRACT_DIGEST_V3": features.feature_contract_fingerprint(),
        "FEATURE_ENCODING_DIGEST_V3": features.encoding_contract_fingerprint(),
        "FEATURES_SOURCE_SHA256_V3": source_hash,
        "FEATURE_DESCRIPTOR_SHA256_V3": hashlib.sha256(descriptor_bytes).hexdigest(),
    }
    lines = ["// Generated by data/flat_policy_v3/generate_contract.py. V5 pins are separate."]
    lines += [f'pub(crate) const {key}: &str = "{value}";' for key, value in values.items()]
    (directory / "feature_identity.rs").write_bytes(("\n".join(lines) + "\n").encode())
    print(json.dumps(values, sort_keys=True))


if __name__ == "__main__":
    generate()
